version: '3.8'
services:
  app:
    build: .
    container_name: whatsapp-router
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    volumes:
      - .:/app
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-tunnel
    depends_on:
      - app
    command: tunnel --no-autoupdate run
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    # For production, mount /etc/cloudflared for credentials if needed
    # volumes:
    #   - ./cloudflared:/etc/cloudflared
